# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=30)),
                ('desc', models.CharField(default='', max_length=1000, null=True, verbose_name='Describe your organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=1000, null=True, verbose_name='Describe yourself')),
                ('email', models.CharField(default='', max_length=100, null=True, verbose_name='Your Email')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
