# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='business',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ManyToManyField(to='userauth.Organization'),
        ),
    ]
