# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 01:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20161008_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pay_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.Organization')),
            ],
        ),
    ]
