# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_payoutsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutsetting',
            name='block_size',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutsetting',
            name='reserve',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
